v12mike_sitemap_sitemapindex:
    path: /sitemap.xml
    defaults: { _controller: v12mike.sitemap.sitemap:index }
v12mike_sitemap_sitemap:
    path: /sitemap/f={forum}/t={start}.xml
    defaults: { _controller: v12mike.sitemap.sitemap:sitemap }
    requirements:
        forum: '\d+'
        start: '\d+'
