services:
    v12mike.sitemap.sitemap:
        class: v12mike\sitemap\controller\sitemap
        arguments:
            - '@auth'
            - '@config'
            - '@dbal.conn'
            - '@controller.helper'
            - '@dispatcher'
            - '@content.visibility'
            - '%core.php_ext%'
            - '@ext.manager'
